main/urls.py
from django.urls import path
from .views import IndexView, manager

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('manager/', manager, name='manager'),
]

yummy_april/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import IndexView, manager
from yummy_april import settings
from django.conf.urls.static import static
from account.views import RegisterView, MyLoginView, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),

    path('manager/', manager, name='manager'),
    path('', include('main.urls')),

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Yummy Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
    <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
    <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
    <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
    <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href={% static "assets/css/main.css" %} rel="stylesheet">
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">
            <a href="{% url 'main:index' %}" class="logo d-flex align-items-center me-auto me-lg-0">
                <h1>{{ app_title|safe }}</h1>
            </a>

            {% include 'includes/nav.html' %}



            <a class="btn-book-a-table" href="#book-a-table">Book a Table</a>
            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
        </div>
        <div>
            {% include 'includes/messages.html' %}
        </div>
    </header>
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>

    <!-- ======= Footer ======= -->
    {% include 'includes/footer.html' %}
    <!-- End Footer -->
    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
    <script src={% static "assets/vendor/aos/aos.js" %}></script>
    <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
    <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
    <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>
    <!-- Template Main JS File -->
    <script src={% static "assets/js/main.js" %}></script>
</body>
</html>